Adds simple CSW harvesting
ioos/catalog-harvesting pull request #33
Opened 2016-11-16 22:00 UTC by benjwadams

2016-11-17 12:57 UTC, lukecampbell commented on catalog_harvesting/harvest.py
> +            count += 1
These nested trys inside a for-loop needs to be refactored into separate functions.

2016-11-17 12:58 UTC, lukecampbell requested changes

2016-11-17 12:58 UTC, lukecampbell commented on catalog_harvesting/harvest.py
> +        print(rec)
Please use logger over prints

2016-11-17 14:58 UTC, benjwadams commented on catalog_harvesting/harvest.py
> +        print(rec)
I'm just going to remove that entirely, was for debug and forgot to remove it.

2016-11-18 14:43 UTC, lukecampbell requested changes

2016-11-18 14:43 UTC, lukecampbell commented on catalog_harvesting/harvest.py
> +            print(file_loc)
use logging please

2016-11-18 14:43 UTC, lukecampbell commented on catalog_harvesting/harvest.py
> +            print(file_loc)
Please use logging

2016-11-18 20:58 UTC, lukecampbell approved these changes

2016-11-18 20:58 UTC, merged